# Generated by Django 4.2.1 on 2024-08-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
    ]
